# Generated by Django 5.0.6 on 2024-06-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_supermarket_address_remove_supermarket_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro')], max_length=3),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramm'), ('g', 'Gramm'), ('l', 'Liter'), ('ml', 'Milliliter')], max_length=2),
        ),
    ]
