# Generated by Django 5.0.6 on 2024-06-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_purchase_currency_alter_purchase_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramm'), ('g', 'Gramm'), ('l', 'Liter'), ('ml', 'Milliliter')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
