# Generated by Django 5.0.6 on 2024-06-26 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_purchase_unit_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro')], max_length=3, verbose_name='Währung'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(verbose_name='Kaufdatum'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Größe'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supermarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.supermarket', verbose_name='Supermarkt'),
        ),
    ]
